---
platform: linux
inputs:
- name: git-repo
outputs:
- name: distribution-repository
- name: git-repo
caches:
- path: maven
- path: gradle
params:
  BRANCH:
  CI: true
  SMOKE_TEST:
  TASK:
  DOCKER_HUB_MIRROR:
run:
  path: bash
  args:
    - -ec
    - |
      mkdir -p /root/.docker
      cat > /root/.docker/config.json <<EOF
      { "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_HUB_AUTH" }}}
      EOF
      source /docker-lib.sh
      start_docker $DOCKER_HUB_MIRROR
      ${PWD}/git-repo/ci/scripts/smoke-test.sh
