spring:
  application:
      name: context-refresh
  config:
    import: file:./cloud/context-refresh/dev.properties

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
