spring:
  cloud:
    refresh:
      on-start:
        enabled: false
  application:
      name: context-refresh-http
  config:
    import: file:./cloud/context-refresh-http/dev.properties

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
